tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "thatrobotdev/sketch-versions"
brew "git"
brew "mas"
brew "youtube-dl"
cask "1password"
cask "adobe-creative-cloud"
cask "anki"
cask "cloudflare-warp"
cask "cryptomator"
cask "discord"
cask "flux"
cask "github"
cask "google-drive"
cask "google-chrome"
cask "handbrake"
cask "hazeover"
cask "hiddenbar"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keka"
cask "kekaexternalhelper"
cask "macfuse"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "notion"
cask "obsidian"
cask "optimage"
cask "sensiblesidebuttons"
cask "sketch@70.4"
cask "slack"
cask "standard-notes"
cask "thingsmacsandboxhelper"
cask "ti-connect-ce"
cask "tor-browser"
cask "unity-hub"
cask "visual-studio-code"
cask "vlc"
mas "Developer", id: 640199958
mas "Focused Work - Pomodoro Timer", id: 1523968394
mas "GIPHY CAPTURE", id: 668208984
mas "In Your Face", id: 1476964367
mas "Magnet", id: 441258766
mas "Things", id: 904280696
mas "Webp Converter", id: 1527716894
mas "Xcode", id: 497799835
