#!/usr/bin/env bash

# Color
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

display_help () {
  echo "Example usage:"
  echo "  ./install [-h, -n]"
  echo;
  echo "Installs or updates configuration dotfiles for macOS."
  echo -e "All errors are typed in ${RED}RED${NC}, installing is denoted in ${GREEN}GREEN${NC}, and logging starts with the \"⚙\" symbol."
  echo;
  echo "Options:"
  echo "  -h, --help          displays description and options"
  echo "  -n, --no-homebrew   skips Homebrew config when passed"
}

while :
do
  case "$1" in
    -h | --help)
      display_help
      exit 0
      ;;
    -n | --no-homebrew)
      nohomebrew="nohomebrew"
      shift
      ;;
    # --) # End of all options
    #   shift
    #   break;
    -*)
      echo -e "${RED}⚙ Error: Unknown option: $1" >&2
      exit 1
      ;;
    *) # No more options
      break
      ;;
  esac
done

echo "⚙ Setting up your Mac... (get help with \"-h\" or \"--help\")"

# Homebrew config if user doesn't pass a -nh or --no-homebrew argument
if [ "$nohomebrew" ]; then
    echo "⚙ Skipping Homebrew recipe update."
    else

    echo "⚙ Starting Homebrew config..."
    
    # Check for Homebrew and install if we don't have it
    if test ! $(which brew); then
        echo -e "${GREEN}⚙ Installing Homebrew${NC}"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    else
      echo "⚙ Homebrew found."
    fi
    
    echo "⚙ Updating Homebrew..."
    brew update

    # Install all our dependencies with bundle (See Brewfile)
    echo "⚙ Installing all our dependencies with bundle..."
    brew tap homebrew/bundle
    brew bundle

    echo "⚙ Upgrade outdated casks and outdated, unpinned formulae..."
    brew upgrade

    echo "⚙ Allow system Java wrappers to find JDKs"
    sudo ln -sfn $(brew --prefix)/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
    sudo ln -sfn $(brew --prefix)/opt/openjdk@8/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-8.jdk

fi
shift

# Install Oh My ZSH (https://github.com/ohmyzsh/ohmyzsh) if it isn't installed 

if [ ! -d $HOME/.oh-my-zsh ]; then
  echo -e "${GREEN}⚙ Installing Oh My ZSH...${NC}"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
else
  echo "⚙ Oh My ZSH found."
fi

# Dotbot
echo "⚙ Booting up Dotbot..."

########################################################
### FROM DOTBOT INSTALL FILE

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

########################################################

# Restoring macOS configs with mackup
echo "⚙ Restoring macOS configs with mackup..."
mackup restore

echo "⚙ Backing up current configuration..."
mackup backup

echo "⚙ Ayy we good"
