tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "mas"

# Browsers
cask "firefox"

# Passwords
cask "1password"

# Productivity
mas "Focused Work - Pomodoro Timer", id: 1523968394

# Programming
cask "github"
cask "visual-studio-code"